### ISSUE TITLE
HDMI Question

### ISSUE THREAD

**Issue by gatorback** [sambow23/HP-ZBook-Firefly-14-G7-Hackintosh#1]
First, this is brilliant work and well documented.  Thank you

Test devices:  

* G7 14  Firefly outfittedCore i5 10210U Quad Core 1.6 GHz / 4.2Ghz turbo
* an USB-C external docking bay (J5 Create JCD3198) 

It is indicated that the HDMI suffers from HP firmware.  HDMI out does not work with this EFI.   How did you know that the firmware was faulty and where can I read more?  How do you connect to an external monitor?

The EFI detects the docking bay's HDMI and max resolution is 2560X1440.   What needs to be done to increase it up to 4K?

**Comment by sambow23** [comment]
> It is indicated that the HDMI suffers from HP firmware. HDMI out does not work with this EFI. How did you know that the firmware was faulty and where can I read more? How do you connect to an external monitor?

I was having issues using the HDMI port on Ubuntu/NixOS and iirc I did some googling and found posts like [these](https://forums.linuxmint.com/viewtopic.php?t=383106). The same issue persists in macOS and mapping the HDMI port manually doesn't do anything. I can connect external monitors using my Caldigit TS3 Plus thunderbolt dock or just a normal USB-C to DisplayPort cable.

As for the limited resolution on the USB-C dock, the limitation could be down to the dock itself or a limitation with the SMBIOS/iGPU not being able to support higher clock rates over DisplayPort. I have a 4K display as well and I ran into the same issue without anything to solve it.
