### ISSUE TITLE
USB-A USB ports on Docking bay configuration

### ISSUE THREAD

**Issue by gatorback** [sambow23/HP-ZBook-Firefly-14-G7-Hackintosh#2]
Kudos for configuring the power percentage indicator: nice win.

USB-A ports on an USB-C external docking bay (J5 Create JCD3198) were successfully tested with yusufklncc EFI:

https://github.com/yusufklncc/HP-EliteBook-840-G7-Hackintosh

Unfortunately, I was not able to repeat this with the sambow23 EFI.   I do not understand USB mapping well enough to pinpoint the difference between the two EFIs.   Perhaps you might have some insight as to why the jusufklncc USB port mapping somehow enables the docking bay's USB-A ports?  Thank you

**Comment by sambow23** [comment]
Depending on how your dock interacts with the laptop's USB controller could give some idea. My mapping in theory shouldn't interfere with other USB-C docks. My CalDigit TS3 Plus and Dell Universal Dock D6000 work perfectly fine with my EFI so I'm unsure why yours wouldn't work.
