### ISSUE TITLE
Is Bluetooth tested?

### ISSUE THREAD

**Issue by gatorback** [sambow23/HP-ZBook-Firefly-14-G7-Hackintosh#3]
Greetings, have you tested BT with the Intel comms?  I ask because if there is some reason it will never work, I would like to know before embarking on a snipe hunt.   I realize that .md page indicates it is untested, however, I thought it made sense ask in case you have tested it since then.  Thanks

**Comment by sambow23** [comment]
Nope, still haven't. Though since it's a normal intel wifi/bt chip it shouldn't be too much effort to get it up and running:
https://openintelwireless.github.io/IntelBluetoothFirmware/
