### ISSUE TITLE
How to add battery percentage monitoring capability to Opencore

### ISSUE THREAD

**Issue by gatorback** [sambow23/HP-ZBook-Firefly-14-G7-Hackintosh#4]
I would like to learn the theory / background necessary to:

* add .kexts or other similar files
* modifications / settings to config.plist
* BIOS settings
* anything else I may have missed

Please advise a list of links and any lessons learned with regard to theory / background?  Thank you for taking the time to answer my questions.

**Comment by sambow23** [comment]
Everything I have learned I followed from this guide
https://dortania.github.io/OpenCore-Install-Guide/
I can't give any input for BIOS settings as this laptop has a BIOS password that I can't remove. Though it's safe to assume the default settings are fine. As for laptop specific quirks, I had to google around myself.
